services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BD\EzPlatformGraphQLForm\GraphQL\FormFieldValueBuilder:
        tags:
            - { name: ezplatform_graphql.field_value_builder, type: 'ezform'}

    BD\EzPlatformGraphQLForm\GraphQL\FormResolver:
        tags:
            #- { name: overblog_graphql.resolver, alias: "PageBlockAttributeType", method: "resolvePageBlockAttributeType" }

    BD\EzPlatformGraphQLForm\GraphQL\FormSchemaBuilder:
        tags:
            - {name: ezplatform_graphql.schema_builder}